### ISSUE TITLE
Add the ability for searches to be ephemeral 

### ISSUE THREAD

**Issue by astridlol** [SantioMC/MinehutUtils#2]
Adding a "silent" argument to each command, which changes the ephemeral status could be cool.

**Comment by SantioMC** [comment]
There's no reason for this to really exist, since you can always just DM the bot, example below:
![image](https://user-images.githubusercontent.com/30200259/189002240-ad94a44a-42a4-4595-985e-61b499567bd2.png)

**Comment by astridlol** [comment]
That works too, I guess it would also clutter up arguments and add more logic to the code if it were added. I forgot the commands were global as well
